from .examples.sir import SIR
from .examples.seir import SEIR
from .examples.seidr import SEIDR
from .examples.seihdr import SEIHDR
from .examples.granular_sir import GranularSIR
from .examples.covid import COVID19
from .examples.covid_category import COVID19Category
from .examples.covid_prodromal import COVID19Prodromal
from .model import CompartmentalModel